### ISSUE TITLE
🪄 Enhancement - How can I custom pattern phone because I see some wrongs

### ISSUE THREAD

**Issue by phanvungoc96** [typesnippet/react-phone-hooks#19]
### Summary

When I select Singapore flags, the pattern should be +65 XXXX XXXX XXX  but I received is +65 (XXXX) XXX XXXX. It make me get some mistake.

I can't change pattern because no any props.

Please help me

**Comment by ArtyomVancyan** [comment]
Hi @phanvungoc96, the area code must be wrapped with parenthesis - it is used for parsing the phone metadata from a formatted string. But we can change "[+65 (XXXX) XXX XXXX](https://github.com/typesnippet/react-phone-hooks/blob/master/src/metadata/countries.json#L1902)" to "+65 (XXXX) XXXX XXX". Unfortunately, input masks are not customizable. Please feel free to open a pull request if you'd like to change Singapore's input mask, and I'll include it in future releases.
