### ISSUE TITLE
🪄 Enhancement - Add option to only show country prefixes in dropdown instead of multiple entries with area codes

### ISSUE THREAD

**Issue by redpandatronicsuk** [typesnippet/react-phone-hooks#38]
### Summary

When typing `Un` it shows multiple entries for United States and the one without any area codes is not at the top of the list. I think for most users it is more convenient to add to enter the 3-digit area code than finding it in a relatively large list.

<img width="160" alt="image" src="https://github.com/typesnippet/antd-phone-input/assets/8609582/f2fa2d04-c348-4964-8fe2-781e49aeebd2">

**Comment by ArtyomVancyan** [comment]
Hey @redpandatronicsuk, good news! The feature you have requested is now available on the [latest release](https://github.com/typesnippet/react-phone-hooks/releases/tag/v0.1.7) of this package, which means you can now reinstall your `antd-phone-input` so it pulls the latest version of its dependency. You can achieve the above-described behavior by excluding special dial codes you don't want to appear.

### Approach 1

```javascript
<PhoneInput
    onlyCountries={["ae", "gb", "us"]}
    excludeCountries={["1907", "1205", "1251", "1256"]}
/>
```
### Approach 2

```javascript
<PhoneInput
    onlyCountries={["ae", "gb", "1"]}
/>
```
