### ISSUE TITLE
ReferenceError: document is not defined, when used with Next.JS

### ISSUE THREAD

**Issue by MuhammadSabah** [typesnippet/react-phone-hooks#43]
### Bug description

The problem comes from the package `react-phone-hooks`
exactly is this file `node_modules/react-phone-hooks/styles.js`

### Screenshots

![DESCRIPTION](LINK.png)

### Logs
- error node_modules/react-phone-hooks/styles.js (12:0) @ injectStyles
- error ReferenceError: document is not defined
_No response_

**Comment by ArtyomVancyan** [comment]
@MuhammadSabah, I want to thank you for reporting the issue and providing a sample application so I could reproduce the cause of the issue and fix it. You can now reinstall the packages so the version of the `react-phone-hooks` gets upgraded, and the issue doesn't appear anymore.
