### ISSUE TITLE
🪄 Enhancement - Bad Spain Number Format

### ISSUE THREAD

**Issue by guiolmar** [typesnippet/react-phone-hooks#45]
### Summary

I was looking for a library to improve my application's phone number input using Ant. This library is great! But we can't use it because we are from Spain and the format of the numbers is incorrect. In Spain we don't have area codes.
Example number: 600111222

![Screenshot 2024-07-26 at 16 00 40](https://github.com/user-attachments/assets/fac4ae4d-5be1-4eb7-8248-498982805d8e)

The correct format would be **+34 603 78 15 15** not +34 (603) 781 515

**Comment by guiolmar** [comment]
@ArtyomVancyan Thank you man! <3

**Comment by ArtyomVancyan** [comment]
Hi @guiolmar, the #47 fix is now included in the latest release of `react-phone-hooks`, so you can upgrade it `^0.1.10` and enjoy.

**Comment by guiolmar** [comment]
Hi @ArtyomVancyan, thank you so much. Awesome job! 🙌🏻

**Comment by guiolmar** [comment]
@ArtyomVancyan , Part of what was wrong is that in Spain we don't have parentheses. Correct format: ... .. .. ..
Now it seems the format is still using them. I have tried updating the package and removing the parentheses in the contries.json but I can't get them to be removed from the input.
<img width="378" alt="Screenshot 2024-08-05 at 17 29 50" src="https://github.com/user-attachments/assets/dec519de-c945-41bb-a0d9-9483dcddbea4">
<img width="290" alt="Screenshot 2024-08-05 at 17 30 21" src="https://github.com/user-attachments/assets/90a0f7a5-3a52-45f9-90f1-dc5696e9385e">
So the format is still incorrect. Plus I can't fix it, otherwise I would have already made a PR. As I said in the first issue message: The correct format would be +34 603 78 15 15 not +34 (603) 78 15 15

**Comment by ArtyomVancyan** [comment]
@guiolmar, not all countries use parenthesis that is why the phone component has the `disableParentheses` boolean property so you can disable it.
