### ISSUE TITLE
🐛 Bug Report Incorrect phone mask for Russia

### ISSUE THREAD

**Issue by aacheblukov** [typesnippet/react-phone-hooks#9]
### Bug description

You should change Russia phone mask from "+7 (...) ... ... ....." to "+7 (...) ... .. .." since it has 10 digits after country code: https://en.wikipedia.org/wiki/Telephone_numbers_in_Europe

### Reproduction steps

1. Select Russia's country code
2. Type any digits to the limit
3. There must be 10 digits after country code

### Screenshots

![image](https://github.com/typesnippet/react-phone-hooks/assets/32964361/a39e9d1f-5972-489a-9e11-52b6b0cfdb06)

**Comment by ArtyomVancyan** [comment]
Hi @Andrew, thank you for the report. Yes, you're almost right :) Phone numbers in russia primarily consist of 10 digits, but there are exceptional cases like [UAN numbers](https://github.com/google/libphonenumber/blob/master/resources/PhoneNumberMetadata.xml#L25279) that have up to 14 numbers of possible length. It is highlighted in the Google's [libphonenumber](https://github.com/google/libphonenumber/) which is a project that [react-phone-hooks](https://github.com/typesnippet/react-phone-hooks) leverages on. Also, take a look at [this](https://en.wikipedia.org/wiki/Telephone_numbers_in_Russia#International_calls_from_Russia) Wikipedia article that has an example.

**Comment by aacheblukov** [comment]
Got it, thank you for the quick response!
In this case, I assume it would be correct to add one more mask for specific UAN numbers that start with 800-804 as it's mentioned there https://github.com/google/libphonenumber/blob/master/resources/PhoneNumberMetadata.xml#L25279
